
title: Simplify4U
url: https://www.simplify4u.org
baseurl: /

permalink: /:categories/:title.html

tags_path: tags.html
paginate: 25

markdown: kramdown
excerpt_separator: "<!-- -->"

github: [metadata]

plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
