
title: Simplify4U
url: https://www.simplify4u.org
baseurl: /

permalink: /:title.html

tags_path: tags.html
paginate: 5

markdown: kramdown
excerpt_separator: "<!-- -->"

github: [metadata]

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
